name: Actions workflow
on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List the contents 
        run: |
          pwd
          ls
          
      - name: Checkout
        uses: actions/checkout@v1

      - name: List the contents 
        run: |
          pwd
          ls

      - name: Simple javascript action
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Dharan

      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
