name: Setting up my first workflow
on: push
  # schedule:
  #   - cron: "0/5 * * * *"

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World1"
      - name: executing multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor());
        shell: python

      - name: Github events
        env:
          EVENT_CONTEXT: ${{toJSON(github.events)}}
        run: |
          echo $EVENT_CONTEXT

